CREATE TABLE IF NOT EXISTS address  (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  STREET VARCHAR(50) NOT NULL,
  STREET_NUMBER VARCHAR(10),
  CITY VARCHAR(20) NOT NULL,
  ZIP_CODE VARCHAR(10) NOT NULL,
  COUNTRY VARCHAR(20) NOT NULL,
  PRIMARY KEY(ID)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS customer  (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(50) NOT NULL,
  ID_ADDRESS BIGINT NOT NULL,
  PRIMARY KEY(ID),
  FOREIGN KEY(ID_ADDRESS) REFERENCES address(ID)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS product  (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(50) NOT NULL,
  PRIMARY KEY(ID)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS category  (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(50) NOT NULL,
  PRIMARY KEY(ID)
) ENGINE=InnoDB;


CREATE TABLE IF NOT EXISTS product_categories  (
ID_PRODUCT BIGINT NOT NULL,
ID_CATEGORY BIGINT NOT NULL,
PRIMARY KEY(ID_PRODUCT, ID_CATEGORY),
FOREIGN KEY(ID_PRODUCT) REFERENCES product(ID),
FOREIGN KEY(ID_CATEGORY) REFERENCES category(ID)
) ENGINE=InnoDB;


CREATE TABLE IF NOT EXISTS invoice  (
  INVOICE_NUMBER BIGINT NOT NULL AUTO_INCREMENT,
  /*CUSTOMER_NAME VARCHAR(50) NOT NULL,*/
  ORDER_NUMBER VARCHAR(13),
  ID_CUSTOMER BIGINT NOT NULL,
  PRIMARY KEY(INVOICE_NUMBER),
  FOREIGN KEY(ID_CUSTOMER) REFERENCES customer(ID)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS invoice_line  (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  QUANTITY SMALLINT NOT NULL,
  ID_PRODUCT BIGINT NOT NULL,
  INVOICE_NUMBER BIGINT NOT NULL,
  PRIMARY KEY(ID),
  FOREIGN KEY(INVOICE_NUMBER) REFERENCES invoice(INVOICE_NUMBER),
  FOREIGN KEY(ID_PRODUCT) REFERENCES product(ID)
) ENGINE=InnoDB;
