CREATE TABLE IF NOT EXISTS actor  (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  FIRST_NAME VARCHAR(20) NOT NULL,
  LAST_NAME VARCHAR(20),
  PRIMARY KEY(ID)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS movie (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  TITLE VARCHAR(20) NOT NULL,
  GENRE VARCHAR(20) NOT NULL,
  DESCRIPTION VARCHAR(255),
  ID_MAIN_ACTOR BIGINT NOT NULL,
  PRIMARY KEY(ID),
  FOREIGN KEY(ID_MAIN_ACTOR) REFERENCES actor(ID)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS movie_sec_actors(
ID_MOVIE BIGINT NOT NULL,
ID_ACTOR BIGINT NOT NULL,
PRIMARY KEY (ID_MOVIE,ID_ACTOR),
FOREIGN KEY(ID_MOVIE) REFERENCES movie(ID),
FOREIGN KEY(ID_ACTOR) REFERENCES actor(ID)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS app_user(
ID BIGINT NOT NULL AUTO_INCREMENT,
USERNAME VARCHAR(50) NOT NULL,
PRIMARY KEY (ID)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS review(
ID BIGINT NOT NULL AUTO_INCREMENT,
ID_MOVIE BIGINT NOT NULL,
ID_REVIEWER BIGINT NOT NULL,
MARK SMALLINT NOT NULL,
REVIEW_COMMENT VARCHAR(255),
PRIMARY KEY (ID),
FOREIGN KEY(ID_MOVIE) REFERENCES movie(ID),
FOREIGN KEY(ID_REVIEWER) REFERENCES app_user(ID)
) ENGINE=InnoDB;


